# Generated by Django 3.0.4 on 2020-04-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200424_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'approved'), ('denied', 'denied'), ('Not Confi', 'sedan')], default='LBS', max_length=200),
        ),
    ]
