# Generated by Django 3.0.4 on 2020-04-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_ride_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'approved'), ('denied', 'denied'), ('not confirmed', 'not confirmed')], default='not confirmed', max_length=200),
        ),
    ]
