# Generated by Django 3.0.4 on 2020-04-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200424_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'approved'), ('denied', 'denied'), ('not_confirmed', 'not_confirmed')], default='not_confirmed', max_length=200, null=True),
        ),
    ]
