# Generated by Django 3.0.4 on 2020-04-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200425_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'approved'), ('denied', 'denied'), ('not_confirmed', 'not_confirmed')], default='not_confirmed', max_length=200),
        ),
    ]
