# Generated by Django 3.0.4 on 2020-04-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200425_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='car_drop',
            field=models.CharField(choices=[('NHR', 'NHR'), ('AZD', 'AZD'), ('LBS', 'LBS'), ('MS', 'MS'), ('MMM', 'MMM'), ('BRH', 'BRH'), ('RK', 'RK'), ('RP', 'RP'), ('MT', 'MT'), ('SN', 'SN'), ('Airport', 'Airport'), ('KGP Railway', 'KGP Railway'), ('Hijli Railway', 'Hijli Railway')], default='LBS', max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='car_pickup',
            field=models.CharField(choices=[('NHR', 'NHR'), ('AZD', 'AZD'), ('LBS', 'LBS'), ('MS', 'MS'), ('MMM', 'MMM'), ('BRH', 'BRH'), ('RK', 'RK'), ('RP', 'RP'), ('MT', 'MT'), ('SN', 'SN'), ('Airport', 'Airport'), ('KGP Railway', 'KGP Railway'), ('Hijli Railway', 'Hijli Railway')], default='AZD', max_length=200),
        ),
    ]
