# Generated by Django 3.0.4 on 2020-04-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20200425_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
