# Generated by Django 3.0.4 on 2020-04-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_car_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='completed',
        ),
        migrations.AddField(
            model_name='ride',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
