# Generated by Django 3.0.4 on 2020-04-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='driver',
            field=models.CharField(max_length=200),
        ),
    ]
